language: python

sudo: false

python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3.5

install:
  - python setup.py sdist
  - pip install dist/doublex-expects-`python setup.py --version`.tar.gz
  - pip install -r test-requirements.txt

script:
  - mamba

deploy:
  provider: pypi
  skip_cleanup: true
  user: jaimegildesagredo
  password:
    secure: YuA1aIn3dcqbemRGQWQXbcZ4Qaj+Bf36nexggbx6I+VpLF9F6vLcQRciLO14IMMKOTWkfnRgF3G2TXSapIZmCKq/kWa2QjS9i3LGF3zicstrXaZXVij5DBd3l0W0PyKYgSyLo7zKPC56lHVV7dERl8z9A8w8W5axzFZGGYbSvMU=
  on:
    tags: true
    repo: jaimegildesagredo/doublex-expects
    python: 3.6
